---
- name: Check my websites
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - files/websites.yml

  tasks:

    - name: Walking through my list of urls on port 80
      delegate_to: 127.0.0.1
      loop: "{{ websites }}"
      register: websites_status_port_80
      failed_when: websites_status_port_80['status'] is not defined
      ansible.builtin.uri:
        url: "http://{{ item['url'] }}"
        method: GET
        return_content: false
        status_code: [200, 404]

    - name: Print out websites_status_port_80
      no_log: true
      loop: "{{ websites_status_port_80['results'] }}"
      ansible.builtin.debug:
        msg: "redirected:{{ item['redirected'] }} url:{{ item['url'] }} status:{{ item['status'] }}"

    - name: Walking through my list of urls on port 443
      delegate_to: 127.0.0.1
      loop: "{{ websites }}"
      register: websites_status_port_443
      failed_when: websites_status_port_443['status'] is not defined
      ansible.builtin.uri:
        url: "https://{{ item['url'] }}"
        method: GET
        return_content: false
        status_code: [200, 404]

    - name: Print out websites_status_port_443
      ansible.builtin.debug:
        var: websites_status_port_443
